// Code generated by scripts/models-gen. DO NOT EDIT.
// Source: pkg/providers/google/models.json

package google

import "github.com/yuri/y/pkg/ai"

// curatedModels is the static fallback model list emitted from models.json.
// Production callers should prefer the live provider models endpoint when
// available. This list is the build-time source of truth used when the
// network is unavailable or no API key is configured.
var curatedModels = []ai.Model{
	{
		ID:            "gemini-2.5-flash",
		Name:          "Gemini 2.5 Flash",
		API:           "google-generative-ai",
		Provider:      "google",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 1000000,
		MaxTokens:     8192,
		Reasoning:     true,
	},
	{
		ID:            "gemini-2.5-pro",
		Name:          "Gemini 2.5 Pro",
		API:           "google-generative-ai",
		Provider:      "google",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 2000000,
		MaxTokens:     8192,
		Reasoning:     true,
	},
}
