// Code generated by scripts/models-gen. DO NOT EDIT.
// Source: pkg/providers/openai/models.json

package openai

import "github.com/yuri/y/pkg/ai"

// curatedModels is the static fallback model list emitted from models.json.
// Production callers should prefer the live provider models endpoint when
// available. This list is the build-time source of truth used when the
// network is unavailable or no API key is configured.
var curatedModels = []ai.Model{
	{
		ID:            "gpt-5",
		Name:          "GPT-5",
		API:           "openai-responses",
		Provider:      "openai",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 256000,
		MaxTokens:     16384,
		Reasoning:     true,
	},
	{
		ID:            "gpt-5-mini",
		Name:          "GPT-5 Mini",
		API:           "openai-responses",
		Provider:      "openai",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 256000,
		MaxTokens:     16384,
		Reasoning:     true,
	},
	{
		ID:            "o3",
		Name:          "o3",
		API:           "openai-responses",
		Provider:      "openai",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 200000,
		MaxTokens:     16384,
		Reasoning:     true,
	},
}
