// Code generated by scripts/models-gen. DO NOT EDIT.
// Source: pkg/providers/openai_compatible/models.json

package openai_compatible

import "github.com/yuri/y/pkg/ai"

// curatedModels is the static fallback model list emitted from models.json.
// Production callers should prefer the live provider models endpoint when
// available. This list is the build-time source of truth used when the
// network is unavailable or no API key is configured.
var curatedModels = []ai.Model{
	{
		ID:            "local-model",
		Name:          "OpenAI-compatible model",
		API:           "openai-completions",
		Provider:      "openai-compatible",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 0,
		MaxTokens:     0,
		Reasoning:     false,
	},
}
