//go:build feature_wasm_ext

package app

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// updateExtensionToggle persists the desired enabled state for a single
// extension id inside a tiny TOML-flavoured registry file alongside the
// main config. Returns true when the on-disk state changed.
//
// The format is intentionally minimal: a single [extensions] table whose
// keys are extension ids and whose values are booleans. This avoids
// pulling a heavyweight TOML parser into the bootstrap path.
func updateExtensionToggle(configPath, id string, enabled bool) (bool, error) {
	if id == "" {
		return false, fmt.Errorf("extension id must be non-empty")
	}
	registryPath := filepath.Join(filepath.Dir(configPath), "extensions.toml")
	state, err := readExtensionRegistry(registryPath)
	if err != nil {
		return false, err
	}
	if existing, ok := state[id]; ok && existing == enabled {
		return false, nil
	}
	state[id] = enabled
	if err := writeExtensionRegistry(registryPath, state); err != nil {
		return false, err
	}
	return true, nil
}

// readExtensionRegistry reads the toggle file. Missing files are treated as
// empty registries so toggles can succeed on a fresh install.
func readExtensionRegistry(path string) (map[string]bool, error) {
	state := make(map[string]bool)
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return state, nil
		}
		return nil, err
	}
	defer f.Close()

	var inSection bool
	scanner := bufio.NewScanner(f)
	for lineNo := 1; scanner.Scan(); lineNo++ {
		raw := stripExtToggleComment(scanner.Text())
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if line != "[extensions]" {
				return nil, fmt.Errorf("%s line %d: only [extensions] is supported", path, lineNo)
			}
			inSection = true
			continue
		}
		if !inSection {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s line %d: expected key = value", path, lineNo)
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		switch value {
		case "true":
			state[key] = true
		case "false":
			state[key] = false
		default:
			return nil, fmt.Errorf("%s line %d: %q must be true or false", path, lineNo, key)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return state, nil
}

// writeExtensionRegistry persists the supplied state, creating the parent
// directory when needed. Keys are emitted in lexical order so the file is
// stable in version control.
func writeExtensionRegistry(path string, state map[string]bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := make([]string, 0, len(state))
	for k := range state {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf strings.Builder
	buf.WriteString("# y extension toggle registry — generated by `y extension enable/disable`.\n")
	buf.WriteString("[extensions]\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "%s = %t\n", k, state[k])
	}
	return os.WriteFile(path, []byte(buf.String()), 0o644)
}

func stripExtToggleComment(line string) string {
	for i, r := range line {
		if r == '#' {
			return line[:i]
		}
	}
	return line
}
