// Code generated by scripts/models-gen. DO NOT EDIT.
// Source: pkg/providers/anthropic/models.json

package anthropic

import "github.com/yuri/y/pkg/ai"

// curatedModels is the static fallback model list emitted from models.json.
// Production callers should prefer the live provider models endpoint when
// available. This list is the build-time source of truth used when the
// network is unavailable or no API key is configured.
var curatedModels = []ai.Model{
	{
		ID:            "claude-haiku-4",
		Name:          "Claude Haiku 4",
		API:           "anthropic-messages",
		Provider:      "anthropic",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 200000,
		MaxTokens:     8192,
		Reasoning:     true,
	},
	{
		ID:            "claude-opus-4",
		Name:          "Claude Opus 4",
		API:           "anthropic-messages",
		Provider:      "anthropic",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 200000,
		MaxTokens:     8192,
		Reasoning:     true,
	},
	{
		ID:            "claude-sonnet-4-5",
		Name:          "Claude Sonnet 4.5",
		API:           "anthropic-messages",
		Provider:      "anthropic",
		Input:         []ai.InputKind{ai.InputText, ai.InputImage},
		ContextWindow: 200000,
		MaxTokens:     8192,
		Reasoning:     true,
	},
}
