// Command models-gen reads a provider's models.json file and writes a
// generated Go file (models_gen.go) containing a typed []ai.Model fallback
// list. It is invoked via `go generate ./pkg/providers/...` and via the
// Makefile `make models` target.
//
// Usage:
//
//	models-gen -provider anthropic -api anthropic-messages \
//	  -input pkg/providers/anthropic/models.json \
//	  -output pkg/providers/anthropic/models_gen.go \
//	  -package anthropic
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type modelEntry struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	ContextWindow int64  `json:"context_window"`
	MaxTokens     int64  `json:"max_tokens"`
	Reasoning     bool   `json:"reasoning"`
	Vision        bool   `json:"vision"`
}

type catalog struct {
	Models []modelEntry `json:"models"`
}

func main() {
	provider := flag.String("provider", "", "provider ID (e.g. anthropic, openai, google)")
	api := flag.String("api", "", "API kind (e.g. anthropic-messages)")
	input := flag.String("input", "", "path to models.json")
	output := flag.String("output", "", "path to write generated Go file")
	pkg := flag.String("package", "", "Go package name")
	flag.Parse()

	if *provider == "" || *api == "" || *input == "" || *output == "" || *pkg == "" {
		fmt.Fprintln(os.Stderr, "usage: models-gen -provider <id> -api <api> -input <path> -output <path> -package <name>")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *input, err)
		os.Exit(1)
	}
	var c catalog
	if err := json.Unmarshal(raw, &c); err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", *input, err)
		os.Exit(1)
	}
	sort.Slice(c.Models, func(i, j int) bool { return c.Models[i].ID < c.Models[j].ID })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by scripts/models-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\n", *input)
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "import \"github.com/yuri/y/pkg/ai\"\n\n")
	fmt.Fprintf(&b, "// curatedModels is the static fallback model list emitted from models.json.\n")
	fmt.Fprintf(&b, "// Production callers should prefer the live provider models endpoint when\n")
	fmt.Fprintf(&b, "// available. This list is the build-time source of truth used when the\n")
	fmt.Fprintf(&b, "// network is unavailable or no API key is configured.\n")
	fmt.Fprintf(&b, "var curatedModels = []ai.Model{\n")
	for _, m := range c.Models {
		var inputs string
		if m.Vision {
			inputs = "{ai.InputText, ai.InputImage}"
		} else {
			inputs = "{ai.InputText}"
		}
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tID:            %q,\n", m.ID)
		fmt.Fprintf(&b, "\t\tName:          %q,\n", m.Name)
		fmt.Fprintf(&b, "\t\tAPI:           %q,\n", *api)
		fmt.Fprintf(&b, "\t\tProvider:      %q,\n", *provider)
		fmt.Fprintf(&b, "\t\tInput:         []ai.InputKind%s,\n", inputs)
		fmt.Fprintf(&b, "\t\tContextWindow: %d,\n", m.ContextWindow)
		fmt.Fprintf(&b, "\t\tMaxTokens:     %d,\n", m.MaxTokens)
		fmt.Fprintf(&b, "\t\tReasoning:     %t,\n", m.Reasoning)
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\noutput:\n%s\n", err, b.String())
		os.Exit(1)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *output, err)
		os.Exit(1)
	}
}
